//create a user
PUT http://localhost:3000/adminproduct/update/5
Content-Type: application/json

{
    
    "productId" : "pm",
    "p_name" : "hr",
    "available" :250,
    "unitPrice" : 23456
  
   
}
//get product
###
GET http://localhost:3000/adminmaterial/view



//logout
###
POST http://localhost:3000/users/signout
Content-Type: application/json

{
    "username" : "admin001",
    "password" : "123456"
}

//add product
###
POST http://localhost:3000/products/addProduct
Content-Type: application/json

{
    
    "pid" : "p02",
    "product_name" : "test",
    "available_product" : 200.00
   
   
}

//get a procut by id
###
GET http://localhost:3000/products/getProduct/7




//login a user
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    
    "username" : "sales002",
    "password" : "123456"
   
}

//create hr manager 
###
POST http://localhost:3000/users/createUser
Content-Type: application/json

{
    "name" : "Buddhi",
    "username" : "hrm001",
    "password" : "123456",
    "confPassword": "123456",
    "role" : "hr_manager"
}



//create finance manager
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Lahiru",
    "username" : "finance001",
    "password" : "123456",
    "confPassword": "123456",
    "role" : "finance_manager"
}


//create Inventory manager
###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "Dhananjaya",
    "username" : "inventory001",
    "password" : "123456",
    "confPassword": "123456",
    "role" : "inventory_manager"
}




###
//get all users
GET http://localhost:5000/users

###
//get a user by id
GET http://localhost:5000/users/bc5afe52-94a2-471a-a1ad-7f0d4af340e0

//update a user
###
PATCH http://localhost:5000/users/80c919bc-ab3e-4ad8-93aa-e08aba56c129
Content-Type: application/json

{
    "name" : "Prageeth updated",
    "username" : "sales002",
    "password" : "",
    "confPassword": "",
    "role" : "sales_manager"
}


//delete a user
###
DELETE http://localhost:5000/users/80c919bc-ab3e-4ad8-93aa-e08aba56c129


//Login user
###
POST http://localhost:5000/login
Content-Type: application/json

{
   
    "username" : "sales001",
    "password" : "123456"
    
}

//Login admin
###
POST http://localhost:5000/login
Content-Type: application/json

{
   
    "username" : "admin001",
    "password" : "123456"
    
}

###
GET http://localhost:5000/me

###
//Logout user
DELETE http://localhost:5000/logout

###
//get all products
GET http://localhost:5000/products

###
//get single products
GET http://localhost:5000/products/6955b3b2-60c2-4df6-a4e0-c203f7943fac


//post data product
###
POST http://localhost:5000/products/
Content-Type: application/json

{
   
    "name" : "Product 4",
    "price" : 150
    
}

//update product
###
PATCH  http://localhost:5000/products/6955b3b2-60c2-4df6-a4e0-c203f7943fac
Content-Type: application/json

{
   
    "name" : "Product UP",
    "price" : 1501
    
}

//delete product
###
DELETE http://localhost:5000/products/81a0e01d-dbcc-45ef-bc01-131ab1ce55e2




